name: queen_validators
description: collection of validation methods and rules for flutter form with ZERO extra widgets
version: 1.0.0
homepage: https://github.com/FlutterQueen/validators
repository: https://github.com/FlutterQueen/validators
issue_tracker: https://github.com/FlutterQueen/validators/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  email_validator: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
