name: queen
repository: https://github.com/FlutterQueen/queen

packages:
  - packages/**
  - queen/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
