name: queen
repository: https://github.com/FlutterQueen/queen

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .
  format:
    exec: flutter format .
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    select-package:
      dir-exists:
        - test
      ignore:
        - "*example*"
