include: package:lint/analysis_options_package.yaml
analyzer:
  errors:
    avoid_classes_with_only_static_members: false
    always_use_package_imports: false
    prefer_relative_imports: true
    use_super_parameters: true
    use_string_buffers: true
    use_rethrow_when_possible: true
    use_raw_strings: true
    use_function_type_syntax_for_parameters: true
    use_full_hex_values_for_flutter_colors: true
    use_enums: true
    use_colored_box: true
