name: Build and Deploy
on:
  push:
    branches:
      - master
    paths:
      - documentation/**
jobs:
  build-and-deploy:
    defaults:
      run:
        working-directory: ./documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.0

        with:
          branch: gh-pages
          folder: ./documentation/build
